#!/bin/sh

OPENWRT=$1

set -e -x

cp "${OPENWRT}"/bin/targets/ar71xx/mikrotik/*-mikrotik-vmlinux-initramfs.elf \
   image/ptpwrt-mikrotik-initramfs.elf
cp "${OPENWRT}"/bin/targets/ar71xx/mikrotik/*-mikrotik-vmlinux-lzma.elf \
   image/ptpwrt-mikrotik-lzma.elf
cp "${OPENWRT}"/bin/targets/ar71xx/mikrotik/*-mikrotik-root.squashfs \
   image/ptpwrt-mikrotik-root.squashfs

exit 0
