#!/bin/sh

OPENWRT=$1

set -e -x

cp "${OPENWRT}"/bin/targets/ar71xx/mikrotik/*-mikrotik-vmlinux-initramfs.elf \
   image/ptpwrt-rb493g-initramfs.elf
cp "${OPENWRT}"/bin/targets/ar71xx/mikrotik/*-mikrotik-vmlinux-lzma.elf \
   image/ptpwrt-rb493g-lzma.elf
cp "${OPENWRT}"/bin/targets/ar71xx/mikrotik/*-mikrotik-root.squashfs \
   image/ptpwrt-rb493g-root.squashfs

exit 0
